### ISSUE TITLE
[Feature Request] Pass channel name to open as cmdline arg

### ISSUE THREAD

**Issue by Racsr** [marcsances/td#14]
The ability to load up directly into a users channel from cmd e.g. npm start --user:marquii or somesuch takes the user to https://www.twitch.tv/marquii on initialization intend of https://www.twitch.tv/.

**Comment by marcsances** [comment]
this was planned in my mind, thanks for calling it, will definitely do

**Comment by marcsances** [comment]
Implemented: ``npm start`` will just open Twitch home, ``npm start ninja`` will open Ninja stream.
