### ISSUE TITLE
Capturing live clips fails.

### ISSUE THREAD

**Issue by Racsr** [marcsances/td#18]
**Describe the bug**
Clicking the Clip button on a live stream opens a child window with a simple Twitch error advising "That clip could not be found."

**To Reproduce**
1. Go to any live stream
2. Click on "Clip"
3. New window opens with error message that clip cannot be found.

**Expected behavior**
The clip edit page should appear allowing the user to edit and save the new clip.

**Screenshots**
<img width="623" alt="2018-05-14 12_13_54-apolloneon - twitch" src="https://user-images.githubusercontent.com/39240796/40009804-03d58238-5771-11e8-8284-5d62281f6692.png">
<img width="1080" alt="2018-05-14 12_15_44-clip not found" src="https://user-images.githubusercontent.com/39240796/40009812-09d23f50-5771-11e8-9fc1-cc38af5fedb4.png">

**Desktop information:**
 - OS: Windows 10 Pro (1709) 16299.431

**Additional context**
N/A

**Logs**
[log.txt](https://github.com/marcsances/td/files/2001684/log.txt) (No additional information appears in the log as the issue occurs)

**Comment by marcsances** [comment]
Issue confirmed, will work on it.
